FROM golang:1.25.4-alpine3.21

WORKDIR /app

# Install air
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Run air
CMD ["air", "-c", ".air.toml"]
