// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goal.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGoalsByUserID = `-- name: ListGoalsByUserID :many
SELECT id, user_id, project_id, target_minutes_per_week, start_date, end_date, created_at, updated_at
FROM goals
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListGoalsByUserID(ctx context.Context, userID pgtype.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.TargetMinutesPerWeek,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGoal = `-- name: UpsertGoal :exec
INSERT INTO goals (id, user_id, project_id, target_minutes_per_week, start_date, end_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, project_id)
DO UPDATE SET target_minutes_per_week = EXCLUDED.target_minutes_per_week,
              start_date = EXCLUDED.start_date,
              end_date = EXCLUDED.end_date,
              updated_at = EXCLUDED.updated_at
`

type UpsertGoalParams struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	ProjectID            pgtype.UUID
	TargetMinutesPerWeek int32
	StartDate            pgtype.Date
	EndDate              pgtype.Date
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpsertGoal(ctx context.Context, arg UpsertGoalParams) error {
	_, err := q.db.Exec(ctx, upsertGoal,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.TargetMinutesPerWeek,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
