// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Goal struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	ProjectID            pgtype.UUID
	TargetMinutesPerWeek int32
	StartDate            pgtype.Date
	EndDate              pgtype.Date
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Note struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Content   string
	Tags      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Project struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type StudyLog struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	StudiedAt pgtype.Timestamptz
	Minutes   int32
	Note      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
