// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: note.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (id, project_id, user_id, title, content, tags, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateNoteParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Content   string
	Tags      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.Exec(ctx, createNote,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteNote = `-- name: DeleteNote :execresult
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteNote, id)
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, project_id, user_id, title, content, tags, created_at, updated_at
FROM notes
WHERE id = $1
`

func (q *Queries) GetNoteByID(ctx context.Context, id pgtype.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesByProjectID = `-- name: ListNotesByProjectID :many
SELECT id, project_id, user_id, title, content, tags, created_at, updated_at
FROM notes
WHERE project_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListNotesByProjectID(ctx context.Context, projectID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :execresult
UPDATE notes SET title = $1, content = $2, tags = $3, updated_at = $4 WHERE id = $5
`

type UpdateNoteParams struct {
	Title     string
	Content   string
	Tags      []string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateNote,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.UpdatedAt,
		arg.ID,
	)
}
