// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, user_id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateProjectParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :execresult
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteProject, id)
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, name, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT id, user_id, name, created_at, updated_at
FROM projects
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListProjectsByUserID(ctx context.Context, userID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :execresult
UPDATE projects SET name = $1, updated_at = $2 WHERE id = $3
`

type UpdateProjectParams struct {
	Name      string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateProject, arg.Name, arg.UpdatedAt, arg.ID)
}
