// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateStudyLog(ctx context.Context, arg CreateStudyLogParams) error
	CreateSubject(ctx context.Context, arg CreateSubjectParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteStudyLog(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
	DeleteSubject(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
	GetStudyLogByID(ctx context.Context, id pgtype.UUID) (StudyLog, error)
	GetSubjectByID(ctx context.Context, id pgtype.UUID) (Subject, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListGoalsByUserID(ctx context.Context, userID pgtype.UUID) ([]Goal, error)
	ListSubjectsByUserID(ctx context.Context, userID pgtype.UUID) ([]Subject, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (pgconn.CommandTag, error)
	UpsertGoal(ctx context.Context, arg UpsertGoalParams) error
}

var _ Querier = (*Queries)(nil)
