// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	CreateStudyLog(ctx context.Context, arg CreateStudyLogParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteProject(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
	DeleteStudyLog(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error)
	GetStudyLogByID(ctx context.Context, id pgtype.UUID) (StudyLog, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListGoalsByUserID(ctx context.Context, userID pgtype.UUID) ([]Goal, error)
	ListProjectsByUserID(ctx context.Context, userID pgtype.UUID) ([]Project, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (pgconn.CommandTag, error)
	UpsertGoal(ctx context.Context, arg UpsertGoalParams) error
}

var _ Querier = (*Queries)(nil)
