// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: studylog.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStudyLog = `-- name: CreateStudyLog :exec
INSERT INTO study_logs (id, user_id, subject_id, studied_at, minutes, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateStudyLogParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	SubjectID pgtype.UUID
	StudiedAt pgtype.Timestamptz
	Minutes   int32
	Note      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateStudyLog(ctx context.Context, arg CreateStudyLogParams) error {
	_, err := q.db.Exec(ctx, createStudyLog,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.StudiedAt,
		arg.Minutes,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const deleteStudyLog = `-- name: DeleteStudyLog :execresult
DELETE FROM study_logs WHERE id = $1
`

func (q *Queries) DeleteStudyLog(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteStudyLog, id)
}

const getStudyLogByID = `-- name: GetStudyLogByID :one
SELECT id, user_id, subject_id, studied_at, minutes, note, created_at
FROM study_logs
WHERE id = $1
`

func (q *Queries) GetStudyLogByID(ctx context.Context, id pgtype.UUID) (StudyLog, error) {
	row := q.db.QueryRow(ctx, getStudyLogByID, id)
	var i StudyLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.StudiedAt,
		&i.Minutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
