// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subject.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :exec
INSERT INTO subjects (id, user_id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSubjectParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) error {
	_, err := q.db.Exec(ctx, createSubject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSubject = `-- name: DeleteSubject :execresult
DELETE FROM subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteSubject, id)
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, user_id, name, created_at, updated_at
FROM subjects
WHERE id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, id pgtype.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjectsByUserID = `-- name: ListSubjectsByUserID :many
SELECT id, user_id, name, created_at, updated_at
FROM subjects
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListSubjectsByUserID(ctx context.Context, userID pgtype.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :execresult
UPDATE subjects SET name = $1, updated_at = $2 WHERE id = $3
`

type UpdateSubjectParams struct {
	Name      string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateSubject, arg.Name, arg.UpdatedAt, arg.ID)
}
